feat(bin): rename cleanup to cleanup-wip because it's still wip

diff --git a/bin/cleanup-wip b/bin/cleanup-wip
--- a/bin/cleanup-wip
+++ b/bin/cleanup-wip
@@ -6,7 +6,7 @@
 # delete the remote branch if it exists.
 #-------------------------------------------------------------------------------
 
-# set -e
+set -e
 
 # ALLBRANCHES=$(gitbranches)
 BRANCHES=()
@@ -37,30 +37,40 @@ checkmark="\033[0;32m\ue63f\033[0m"
 #     echo "$branch " $(git log $branch --max-count=1 | grep "Change-Id:")
 # done
 
-echo hello
 # for branch in $(git for-each-ref refs/heads  | cut -d/ -f3-); do
-for branch in $(gitbranches); do
-  if [ "$branch" != "*" ] && [ "$branch" != "master" ]; then
-    echo "- $branch"
-    changeId=$(git log --max-count=1 $branch | grep "Change-Id:" | trimleading)
-    echo "    - changeId $changeId"
-    if [ -n $changeId ]; then
-      # echo "        - found $changeId"
-      foundInMaster=$(git log master | grep "${changeId}")
-      # echo "-- $foundInMaster"
-      if [ -n $foundInMaster ]; then
-        # echo "            - found in master"
-        BRANCHES+=("$(echo "$checkmark $branch" | trimleading)\n")
+echo hello
+allBranches=( $(git for-each-ref refs/heads  | cut -d/ -f3-) );
+targetBranch=$(git for-each-ref refs/heads  | cut -d/ -f3- | fzf | trimleading) &&
+echo "- targetBranch $targetBranch"
+for branch in $allBranches[@]; do
+  echo "- loop: $branch"
+  if [ "$branch" != $targetBranch ]; then
+    # Get the commit hash from the last commit of a branch
+    commitHash=$(git log --max-count=1 $branch | grep "commit" | cut -d" " -f2)
+    echo "    - $branch commitHash $commitHash"
+    # changeId=$(git log --max-count=1 $branch | grep "Change-Id:" | trimleading)
+    # echo "    - changeId $changeId"
+    if [ -n $commitHash ]; then
+      echo "        - found commit hash: $commitHash"
+      foundInTargetBranch=$(git log $targetBranch --grep "$commitHash")
+      # echo "          - foundInTargetBranch: $foundInTargetBranch"
+      if [ -n $foundInTargetBranch ]; then
+        echo "            - found in $targetBranch"
+        BRANCHES+=("$(echo "$checkmark ${branch}" | trimleading | trimtrailing)")
       else
-        BRANCHES+=("$branch\n")
+        echo "            - |||| not found in $targetBranch"
+        BRANCHES+=("$(echo "$branch" | trimleading | trimtrailing)")
       fi
     else
-        BRANCHES+=("$branch\n")
+      echo "            - $$$$ commit hash not found"
+      BRANCHES+=("$(echo "$branch" | trimleading | trimtrailing)")
     fi
   fi
 done
 echo "---------------------------------------"
-echo $BRANCHES
+for branch in $BRANCHES[@]; do
+  echo $branch
+done
 echo "---------------------------------------"
 # echo $BRANCHES | fzf --ansi -m
 
